# Industry qualitative risk data (policy data)

INDUSTRY_DATA = {
    "Agricultural": {
        "Competitiveness": "UNTHREATENING",
        "Environmental Concerns": "MODERATE",
        "Fiscal Policy Dependence": "HIGH",
        "Business Cyclicality": "LOW",
        "Inflation Sensitivity": "LOW",
        "FX Sensitivity": "LOW",
        "Interest Rate Sensitivity": "MODERATE",
        "Industry Sales Trend": "STABLE",
        "Industry Profitability": "DECREASE",
        "Industry Stage": "STABLE/MATURE",
        "Import Penetration": "HIGH",
        "Industry Failure Rate": "HIGH",
        "Skilled Labor Gap": "FULLYAVAILABLE",
        "Product Positioning": "COMMODITY",
        "Capital Sensitivity": "HIGH",
        "Technology Dependence": "HIGH"
    },

    
    "Construction": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "HIGH",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "DECREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "HIGH",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "CUSTOM",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "MODERATE"
  },

  "Building Materials and Hardware": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "HIGH",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "DECREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Food Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "VERYHIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "SLIGHT",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Forestry, Fisheries and Hunting": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "MODERATE",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "COMMODITY",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Hotels, Restaurants and Drinking Places": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "INSIGNIFICANT",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "DECREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "LOW"
  },

  "Insurance agents, brokers, and service": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "HIGH",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "HIGH",
    "Skilled Labor Gap": "SMALLGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "MODERATE"
  },

  "Chemicals Products Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "VERYHIGH",
    "Fiscal Policy Dependence": "HIGH",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "MODERATE",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "COMMODITY",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Petroleum and Coal Product Manufacturing": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "HIGH",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "HIGH",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "COMMODITY",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Electrical and Electronic Manufacturing": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "VERYHIGH",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "VERYHIGH"
  },

  "Furniture and Fixtures Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "VERYHIGH",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "HIGH",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "LOW"
  },

  
  "Industrial Machinery Manufacturing": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "HIGH",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "HIGH",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "VERYHIGH",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "HIGH",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Instrument Products Manufacturing": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "VERYHIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "VERYHIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "HIGH",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Leather Products Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "VERYHIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "LOW"
  },

  "Lumber and Wood Products Manufacturing": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "DECREASE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "VERYHIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "LOW"
  },

  "Fabricated Metal Product Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "SLIGHT",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "MODERATE"
  },

  "Miscellaneous Manufacturing Industries": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "MODERATE"
  },

  "Paper Product Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "MODERATE"
  },

  "Printing and Publishing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "MODERATE"
  },

  
  "Rubber and Miscellaneous Plastics Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "MODERATE"
  },

  "Stone, Clay, Glass and Concrete Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "MODERATE"
  },

  "Textile Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "MODERATE"
  },

  "Transportation Equipment Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "MODERATE",
    "Technology Dependence": "MODERATE"
  },

  "Membership Organizations": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Primary Metal Industries": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "HIGH",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "MODERATE"
  },

  "Mining": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "HIGH",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "HIGH",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "COMMODITY",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Not Elsewhere Classified": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Oil and Gas Extraction": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "HIGH",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "HIGH",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "COMMODITY",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Automotive Dealers and Service Stations": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Food Stores": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "General Retail": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Miscellaneous Retail": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Business and Engineering Services": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "MODERATE"
  },

  "General Services": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Health Services": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SMALLGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "MODERATE"
  },

  "Legal Services": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SMALLGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Miscellaneous Services": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  
  "Recreational Services": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Education and Social Services": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SMALLGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "MODERATE"
  },

  "Transportation Services": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Telecommunications": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "MODERATE",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "INCREASE",
    "Industry Stage": "GROWTH/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SMALLGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "MODERATE"
  },

  "Tobacco Manufacturing": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "HIGH",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "DECREASE",
    "Industry Profitability": "DECREASE",
    "Industry Stage": "DECLINE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "HIGH",
    "Skilled Labor Gap": "SMALLGAP",
    "Product Positioning": "COMMODITY",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Transportation by Air": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "HIGH",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "HIGH",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "HIGH",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "DECREASE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "HIGH",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Freight and Water Transportation": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "HIGH",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "HIGH",
    "Inflation Sensitivity": "HIGH",
    "FX Sensitivity": "HIGH",
    "Interest Rate Sensitivity": "HIGH",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "DECREASE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "HIGH",
    "Skilled Labor Gap": "LARGEGAP",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "HIGH"
  },

  "Local and Interurban Passenger Transit": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "MODERATE",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Utilities": {
    "Competitiveness": "UNTHREATENING",
    "Environmental Concerns": "HIGH",
    "Fiscal Policy Dependence": "VERYHIGH",
    "Business Cyclicality": "LOW",
    "Inflation Sensitivity": "LOW",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "LOW",
    "Industry Sales Trend": "STABLE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "INSIGNIFICANT",
    "Industry Failure Rate": "LOW",
    "Skilled Labor Gap": "SMALLGAP",
    "Product Positioning": "COMMODITY",
    "Capital Sensitivity": "HIGH",
    "Technology Dependence": "MODERATE"
  },

  "Wholesale Trade - Durable Goods": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  },

  "Wholesale Trade - Nondurable Goods": {
    "Competitiveness": "AGGRESSIVE",
    "Environmental Concerns": "LOW",
    "Fiscal Policy Dependence": "LOW",
    "Business Cyclicality": "MODERATE",
    "Inflation Sensitivity": "MODERATE",
    "FX Sensitivity": "LOW",
    "Interest Rate Sensitivity": "MODERATE",
    "Industry Sales Trend": "INCREASE",
    "Industry Profitability": "STABLE",
    "Industry Stage": "STABLE/MATURE",
    "Import Penetration": "LOW",
    "Industry Failure Rate": "AVERAGE",
    "Skilled Labor Gap": "SOMEPROBLEMS",
    "Product Positioning": "MODERATE",
    "Capital Sensitivity": "LOW",
    "Technology Dependence": "LOW"
  }
}









